comp9321/lab_02_Blueprints/app/models.py
class Teacher:

    def __init__(self, name, course, students={}, username=None, password=None):
        super().__init__()
        self.password = password
        self.username = username
        self.name = name
        self.course = course
        self.students = students


class Student:
    def __init__(self, id, first_name, last_name, gender='MALE'):
        super().__init__()
        self.id = id
        self.first_name = first_name
        self.last_name = last_name
        self.gender = gender

comp9321/lab_02_Blueprints/__init__.py
from lab_02_Blueprints.app.views import bp as controllers
from flask import Flask
app = Flask(__name__)
app.register_blueprint(controllers)

comp9321/lab_02_Blueprints/app/views.py
import datetime

from flask import Blueprint
from flask import request, render_template, redirect, url_for, make_response, session, Flask

from lab_02_Blueprints.app.models import Teacher, Student
from lab_02_Blueprints.utils.serialize import deserialize, serialize

bp = Blueprint('app', __name__, url_prefix='')


@bp.route('/', methods=['GET'])
def index():
    teacher = retrieve_teacher()
    if teacher is None:
        return redirect(url_for(".register"))

    return redirect(url_for(".show_students"))


@bp.route('/register', methods=["POST", "GET"])
def register():
    if request.method == 'GET':
        return render_template("app/register.html")
    else:
        name = request.form.get("name")
        course = request.form.get("course")
        teacher = Teacher(name, course)

        session["_teacher"] = serialize(teacher)
        return redirect(url_for(".index"))


@bp.route('/students', methods=["GET"])
def show_students():
    teacher = retrieve_teacher()
    if teacher is None:
        return redirect("register")
    else:
        return render_template("app/students.html", students=teacher.students.values())


@bp.route('/add', methods=["POST", "GET"])
def add():
    if request.method == 'GET':
        return render_template("app/add.html")
    else:
        id = request.form.get("id")
        firstname = request.form.get("firstname")
        lastname = request.form.get("lastname")
        gender = request.form.get("gender")

        teacher = retrieve_teacher()
        teacher.students[id] = Student(id, firstname, lastname, gender)
        session['_teacher'] = serialize(teacher)

        return redirect(url_for(".show_students"))


@bp.route('/delete/<id>', methods=["GET", "POST", "DELETE"])
def delete(id):
    teacher = retrieve_teacher()
    teacher.students.pop(id)
    session['_teacher'] = serialize(teacher)

    return redirect(url_for(".show_students"))


@bp.route('/edit/<id>', methods=["POST", "GET"])
def edit(id):
    teacher = retrieve_teacher()
    student = teacher.students.pop(id)

    if request.method == 'GET':
        return render_template("app/edit.html", student=student)
    else:
        student.first_name = request.form.get("firstname")
        student.last_name = request.form.get("lastname")
        student.gender = request.form.get("gender")

        teacher.students[id] = student
        session['_teacher'] = serialize(teacher)
        return redirect(url_for(".show_students"))


@bp.route('/save')
def save():
    serialized_teacher = session.get("_teacher")
    resp = make_response(render_template("app/save.html"))
    if serialized_teacher is not None:
        expire_date = datetime.datetime.now() + datetime.timedelta(days=90)
        resp.set_cookie("_teacher", serialized_teacher, expires=expire_date)

    return resp


def retrieve_teacher():
    serialized_teacher = session.get("_teacher")
    if serialized_teacher is None:
        serialized_teacher = request.cookies.get('_teacher')

    if serialized_teacher is not None:
        return deserialize(serialized_teacher)

    return None

comp9321/lab_02_Blueprints/templates/app/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{{url_for('app.add')}}">
    <table>
        <tr>
            <td>id</td>
            <td><input type="number" name="id"></td>
        </tr>
        <tr>
            <td>First name</td>
            <td><input type="text" name="firstname"></td>
        </tr>
        <tr>
            <td>Last name</td>
            <td><input type="text" name="lastname"></td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>
                <select name="gender">
                    <option value="MALE">Male</option>
                    <option value="FEMALE">Female</option>
                </select>
            </td>
        </tr>
        <input type="submit" value="Add" />
    </table>
</form>
</body>
</html>

comp9321/lab_02_Blueprints/templates/app/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{{url_for('app.edit', id=student.id)}}">
    <table>
        <tr>
            <td>id</td>
            <td>{{student.id}}</td>
        </tr>
        <tr>
            <td>First name</td>
            <td><input type="text" name="firstname" value="{{student.first_name}}"></td>
        </tr>
        <tr>
            <td>Last name</td>
            <td><input type="text" name="lastname" value="{{student.last_name}}"></td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>
                <select name="gender">
                    <option value="MALE">Male</option>
                    <option value="FEMALE" {{"selected" if student.gender == 'FEMALE'}} >Female</option>
                </select>
            </td>
        </tr>
    </table>
    <input type="submit" value="Done" />
</form>
</body>
</html>

comp9321/lab_02_Blueprints/templates/app/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<form method="post" action="{{url_for('app.register')}}">
    <table>
        <tr>
            <td>Name</td>
            <td><input type="text" name="name"/></td>
        </tr>
        <tr>
            <td>Course</td>
            <td><input type="text" name="course"/></td>
        </tr>
    </table>
    <input type="submit" value="submit"/>
</form>
</body>
</html>

comp9321/lab_02_Blueprints/templates/app/save.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Saved</title>
</head>
<body>
    <a href='{{url_for("app.show_students")}}' >Return to the students page</a>
</body>
</html>

comp9321/lab_02_Blueprints/templates/app/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Students List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
</head>
<body>

<div class="panel panel-default">
    <div class="panel-heading">Student List</div>
    <div class="table-responsive">
        <table class="table table table-hover">
            <thead>
            <tr>
                <th></th>
                <th></th>
                <th>ID</th>
                <th>Gender</th>
                <th>First Name</th>
                <th class="col-md-10">Last Name</th>
            </tr>
            </thead>
            {% for s in students: %}
            <tr>
                <td><a href="{{url_for('app.edit', id= s.id)}}"><i class="fa fa-pencil-square-o"></i></a></td>
                <td><a href="{{url_for('app.delete', id =s.id)}}"><i class="fa fa-times"></i></a></td>
                <td>{{s.id}}</td>
                <td><i class="{{'fa fa-mars' if s.gender == 'MALE' else 'fa fa-venus'}}"></i>
                <td>{{s.first_name}}</td>
                <td>{{s.last_name}}</td>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

<a class="btn btn-success" href="{{url_for('app.add')}}"><i class="fa fa-venus-mars" aria-hidden="true"></i> New</a>
<a class="btn btn-primary " href="{{url_for('app.save')}}"><i class="fa fa-floppy-o" aria-hidden="true"></i> Save</a>

</body>
</html>